


### /api/copy
post http://localhost:9100/api/copy
Content-Type: application/json

{
  "filePath": ""
}

### /api
post http://localhost:9100/api
Content-Type: application/json

{
  "filePath": "D:\\test\\test.txt"
}

### / 
get http://localhost:9100/